apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: vigneshvicky12345/demo:2
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
  type: NodePort
  
  
